apiVersion: v1
kind: Service
metadata:
  name: aspnetcoreservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aspnetcoreapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcoreapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetcoreapp
  template:
    metadata:
      labels:
        app: aspnetcoreapp
    spec:
      containers:
      - name: aspnetcoreapp
        image: anaselhajjaji/aspnetcoreservice:latest
        ports:
        - containerPort: 80